### ISSUE TITLE
Implement jumping

### ISSUE THREAD

**Issue by MrGallo** [ICS3U-Gallo/cpt-stella#5]
- [x] When you press the appropriate key, set the `player.change_y` to a value 10-30. Observe the different effects.
- [x] Only allow them to jump when they are on the ground.

**Comment by hongs1234** [comment]
The player does go up when I press the button and comes down when I release it, but the player stays in the air during the time in between. So it's not really jumping, more like going up and coming down when pressing and releasing the button
